title: COS Conference Deadlines
description: Countdowns to top CPS conference deadlines
author: Abhishek Das

domain: "ekut-es.github.io"
baseurl: "/cps-deadlines"

twitter_username: 
twitter_hashtag: embeddedsystems
github_username: ekut-es
github_repo: cps-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']
